### ISSUE TITLE
Question: How use it in QtCreator and Ubuntu 22.04 OS?

### ISSUE THREAD

**Issue by parisa-hr** [oltodo/prettier-plugin-qml#54]
Hi
Firstly, I would like to express my gratitude for your impressive project. I appreciate the effort and dedication you have put into it.
I have a question and that is I don't know how to add this program to `QtCreator`.
My OS is `Ubuntu 22.04`.

**Comment by oltodo** [comment]
Hi @parisa-hr 
Thank you very much for your gratitude.
I'm not working on that project for a while since I'm not working on QML at all. But I can try to help.
I just need to figure out what you mean by "add this program to QtCreator".

`prettier-plugin-qml` is actually a plugin for a JS tool named [Prettier](https://prettier.io/) that works with Node.js. So I'd say you probably won't be able to use it inside QtCreator (but I'm not a expert of that IDE that I never really used).

So if your goal is to use this plugin in order to format your QML codebase, you will have to have Node.js (and NPM) installed and execute a command in a terminal in your code's folder (e.g. `prettier --write '**/*.qml'`). You may be able to configure QtCreator to execute this command each time you save a file but I can't help you on this as I don't know that IDE very much.

Note that –as I remember– QtCreator already includes a feature allowing to reformat QML files. I didn't like the output format of this feature at the time, so I created this plugin.

Hope I could help 😉

**Comment by parisa-hr** [comment]
Thank you so much.
